// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Scheduler.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Scheduler.ViewModels;

public partial class AppointmentViewModel
{
    [Key]
    public int Id { get; set; }

    public string Subject { get; set; }


    public DateTime StartTime { get; set; }


    public DateTime EndTime { get; set; }

    public string Location { get; set; }

    public string Description { get; set; }

    public bool IsAllDay { get; set; }

    public bool IsReadonly { get; set; }

    public int? RecurrenceId { get; set; }

    public string RecurrenceRule { get; set; }

    public string RecurrenceException { get; set; }


}