// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Scheduler.Models;

public partial class AppointmentDatum
{
    [Key]
    public int Id { get; set; }

    [Required(ErrorMessage = "Appointment subject is required.")]
    [Display(Name = "Appointment Subject")]
    [StringLength(255, ErrorMessage = "Subject must be 255 characters or less.")]
    public string Subject { get; set; }

    [Required(ErrorMessage = "Start time is required.")]
    [Display(Name = "Start Time")]
    public DateTime StartTime { get; set; }

    [Required(ErrorMessage = "End time is required.")]
    [Display(Name = "End Time")]
    public DateTime EndTime { get; set; }

    [Display(Name = "Location")]
    public string Location { get; set; }

    [Display(Name = "Description")]
    public string Description { get; set; }

    [Display(Name = "All Day")]
    public bool IsAllDay { get; set; }

    [Display(Name = "Read-only")]
    public bool IsReadonly { get; set; }


    [Display(Name = "Recurrence ID")]
    public int? RecurrenceId { get; set; }

    [Display(Name = "Recurrence Rule")]
    public string RecurrenceRule { get; set; }

    [Display(Name = "Recurrence Exception")]
    public string RecurrenceException { get; set; }

}