// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagmentSystem.Models;

public partial class ClassSubject
{
    public int ClassSubjectId { get; set; }

    public int ClassId { get; set; }

    public int SubjectId { get; set; }

    public int TeacherId { get; set; }
    
    public string ClassSubjectName { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();

    public virtual ICollection<Homework> Homeworks { get; set; } = new List<Homework>();

    public virtual Subject Subject { get; set; }

    public virtual Teacher Teacher { get; set; }

    public virtual ICollection<Timetable> Timetables { get; set; } = new List<Timetable>();
}