// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagmentSystem.Models;

public partial class Class
{

    public int ClassId { get; set; }

    public string ClassName { get; set; }

    public string Section { get; set; }

    public string AcademicYear { get; set; }

    public int? HomeroomTeacherId { get; set; }

    public virtual ICollection<ClassSubject> ClassSubjects { get; set; } = new List<ClassSubject>();

    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    public virtual Teacher HomeroomTeacher { get; set; }
}