// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagmentSystem.Models;

public partial class Grade
{
    public int GradeId { get; set; }

    public int EnrollmentId { get; set; }

    public int ClassSubjectId { get; set; }

    public DateOnly? ExamDate { get; set; }

    public decimal? Score { get; set; }

    public string Grade1 { get; set; }

    public virtual ClassSubject ClassSubject { get; set; }

    public virtual Enrollment Enrollment { get; set; }
}