// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagmentSystem.Models;

public partial class HomeworkSubmission
{
    public int SubmissionId { get; set; }

    public int HomeworkId { get; set; }

    public int StudentId { get; set; }

    public string FilePath { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public string Status { get; set; }

    public decimal? Grade { get; set; }

    public virtual Homework Homework { get; set; }

    public virtual Student Student { get; set; }
}