// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolManagmentSystem.Models;

public partial class Timetable
{
    public int TimetableId { get; set; }

    public int ClassSubjectId { get; set; }

    public string DayOfWeek { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public string RoomNumber { get; set; }

    public virtual ClassSubject ClassSubject { get; set; }
}